export const emojis = [
    { emoji: "😀", name: "Grinning Face" },
    { emoji: "😂", name: "Face with Tears of Joy" },
    { emoji: "😍", name: "Heart Eyes" },
    { emoji: "😊", name: "Smiling Face with Smiling Eyes" },
    { emoji: "🔥", name: "Fire" },
    { emoji: "🤔", name: "Thinking Face" },
    { emoji: "😭", name: "Loudly Crying Face" },
    { emoji: "🥰", name: "Smiling Face with Hearts" },
    { emoji: "👍", name: "Thumbs Up" },
    { emoji: "🙌", name: "Raising Hands" },
    { emoji: "😎", name: "Smiling Face with Sunglasses" },
    { emoji: "🎉", name: "Party Popper" },
    { emoji: "💯", name: "Hundred Points" },
    { emoji: "🤯", name: "Exploding Head" },
    { emoji: "👏", name: "Clapping Hands" },
    { emoji: "😅", name: "Grinning Face with Sweat" },
    { emoji: "🙏", name: "Folded Hands" },
    { emoji: "💀", name: "Skull" },
    { emoji: "😢", name: "Crying Face" },
    { emoji: "🤩", name: "Star-Struck" },
    { emoji: "😡", name: "Angry Face" },
    { emoji: "💥", name: "Collision" },
    { emoji: "🌟", name: "Glowing Star" },
    { emoji: "✨", name: "Sparkles" },
    { emoji: "🥺", name: "Pleading Face" },
    { emoji: "🤗", name: "Hugging Face" },
    { emoji: "❤️", name: "Red Heart" },
    { emoji: "😴", name: "Sleeping Face" },
    { emoji: "🤤", name: "Drooling Face" },
    { emoji: "😱", name: "Face Screaming in Fear" },
    { emoji: "🥳", name: "Partying Face" },
    { emoji: "😆", name: "Grinning Squinting Face" },
    { emoji: "🤓", name: "Nerd Face" },
    { emoji: "😜", name: "Winking Face with Tongue" },
    { emoji: "🤪", name: "Zany Face" },
    { emoji: "😇", name: "Smiling Face with Halo" },
    { emoji: "💖", name: "Sparkling Heart" },
    { emoji: "🫶", name: "Heart Hands" },
    { emoji: "👀", name: "Eyes" },
    { emoji: "😈", name: "Smiling Face with Horns" },
    { emoji: "🤡", name: "Clown Face" },
    { emoji: "🤑", name: "Money-Mouth Face" },
    { emoji: "😵", name: "Dizzy Face" },
    { emoji: "🤝", name: "Handshake" },
    { emoji: "🙃", name: "Upside-Down Face" },
    { emoji: "👑", name: "Crown" },
    { emoji: "🎶", name: "Musical Notes" },
    { emoji: "🍀", name: "Four Leaf Clover" },
    { emoji: "💪", name: "Flexed Biceps" },
    { emoji: "🦾", name: "Mechanical Arm" },
    { emoji: "🎂", name: "Birthday Cake" },
    { emoji: "💌", name: "Love Letter" },
    { emoji: "🚀", name: "Rocket" },
    { emoji: "🌍", name: "Globe Showing Europe-Africa" },
    { emoji: "🎨", name: "Artist Palette" },
    { emoji: "⚡", name: "High Voltage" },
    { emoji: "☕", name: "Hot Beverage" },
    { emoji: "🍕", name: "Pizza" },
    { emoji: "🐶", name: "Dog Face" },
    { emoji: "🐱", name: "Cat Face" },
    { emoji: "🏆", name: "Trophy" },
    { emoji: "🎭", name: "Performing Arts" },
    { emoji: "📸", name: "Camera with Flash" },
    { emoji: "🎧", name: "Headphone" },
    { emoji: "🎮", name: "Video Game" },
    { emoji: "🍆", name: "Eggplant" }
];